# Generated by Django 5.2.11 on 2026-03-30 05:08

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("siege_geo", "0004_add_isochrone_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="CongressionalTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "congress_number",
                    models.PositiveSmallIntegerField(
                        help_text="Congress number (1st, 2nd, ..., 119th, ...)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="First day of the term (e.g. 2025-01-03)"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Last day of the term (e.g. 2027-01-03)"
                    ),
                ),
                (
                    "election_year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Year of the general election for this Congress",
                    ),
                ),
                (
                    "is_presidential",
                    models.BooleanField(
                        default=False,
                        help_text="True if a presidential election occurs this cycle",
                    ),
                ),
                (
                    "senate_classes_up",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Senate classes up for election (e.g. [1] or [2, 3])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Congressional Term",
                "verbose_name_plural": "Congressional Terms",
                "ordering": ["congress_number"],
            },
        ),
        migrations.CreateModel(
            name="DistrictDemographics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("acs5", "American Community Survey 5-Year"),
                            ("acs1", "American Community Survey 1-Year"),
                            ("dec", "Decennial Census"),
                            ("dec_pl", "Decennial Census P.L. 94-171"),
                        ],
                        db_index=True,
                        help_text="Census dataset source",
                        max_length=10,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Census/ACS year",
                        validators=[
                            django.core.validators.MinValueValidator(1990),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                    ),
                ),
                ("pop_white", models.BigIntegerField(blank=True, null=True)),
                ("pop_black", models.BigIntegerField(blank=True, null=True)),
                ("pop_hispanic", models.BigIntegerField(blank=True, null=True)),
                ("pop_asian", models.BigIntegerField(blank=True, null=True)),
                ("pop_native", models.BigIntegerField(blank=True, null=True)),
                ("pop_other", models.BigIntegerField(blank=True, null=True)),
                ("pop_two_or_more", models.BigIntegerField(blank=True, null=True)),
                (
                    "median_household_income",
                    models.IntegerField(
                        blank=True,
                        help_text="Median household income (B19013_001E)",
                        null=True,
                    ),
                ),
                (
                    "poverty_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Poverty rate as percentage",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        default=dict, help_text="Variable code -> value mapping"
                    ),
                ),
                (
                    "moe_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variable code -> margin of error mapping",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "District Demographics",
                "verbose_name_plural": "District Demographics",
            },
        ),
        migrations.CreateModel(
            name="PlanDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier for this feature (unique per vintage_year)",
                        max_length=60,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of this feature", max_length=255
                    ),
                ),
                (
                    "vintage_year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Edition year of the source dataset",
                        validators=[
                            django.core.validators.MinValueValidator(1790),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Date this feature became effective (NULL = always valid)",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this feature ceased to be effective (NULL = still valid)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provenance of this feature (e.g. TIGER/Line, GADM, OSM)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boundary_id",
                    models.CharField(
                        db_index=True,
                        help_text="Boundary identifier (synced from feature_id)",
                        max_length=60,
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        help_text="Boundary geometry (WGS 84)", srid=4326
                    ),
                ),
                (
                    "area_land",
                    models.BigIntegerField(
                        blank=True, help_text="Land area in square meters", null=True
                    ),
                ),
                (
                    "area_water",
                    models.BigIntegerField(
                        blank=True, help_text="Water area in square meters", null=True
                    ),
                ),
                (
                    "internal_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Representative interior point (INTPTLAT/INTPTLON)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "geoid",
                    models.CharField(
                        db_index=True,
                        help_text="Full Census GEOID that uniquely identifies this geography",
                        max_length=20,
                    ),
                ),
                (
                    "state_fips",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="2-digit state FIPS code",
                        max_length=2,
                    ),
                ),
                (
                    "lsad",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Legal/Statistical Area Description code",
                        max_length=2,
                    ),
                ),
                (
                    "mtfcc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MAF/TIGER Feature Class Code",
                        max_length=5,
                    ),
                ),
                (
                    "funcstat",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Functional status code from TIGER/Line",
                        max_length=1,
                    ),
                ),
                (
                    "district_number",
                    models.CharField(
                        db_index=True,
                        help_text="District number or identifier within the plan",
                        max_length=10,
                    ),
                ),
                (
                    "polsby_popper",
                    models.FloatField(
                        blank=True,
                        help_text="Polsby-Popper compactness score (0–1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "reock",
                    models.FloatField(
                        blank=True,
                        help_text="Reock compactness score (0–1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "convex_hull_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="Convex hull ratio (0–1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "schwartzberg",
                    models.FloatField(
                        blank=True,
                        help_text="Schwartzberg compactness score (0–1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "total_population",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Total population from Census overlay",
                        null=True,
                    ),
                ),
                (
                    "vap",
                    models.BigIntegerField(
                        blank=True, help_text="Voting age population", null=True
                    ),
                ),
                (
                    "cvap",
                    models.BigIntegerField(
                        blank=True, help_text="Citizen voting age population", null=True
                    ),
                ),
                (
                    "deviation_pct",
                    models.FloatField(
                        blank=True,
                        help_text="Percent deviation from ideal population",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan District",
                "verbose_name_plural": "Plan Districts",
            },
        ),
        migrations.CreateModel(
            name="PlanDistrictAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "boundary_object_id",
                    models.PositiveIntegerField(
                        help_text="PK of the boundary instance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plan District Assignment",
                "verbose_name_plural": "Plan District Assignments",
            },
        ),
        migrations.CreateModel(
            name="PrecinctElectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_fips",
                    models.CharField(
                        db_index=True, help_text="2-digit state FIPS code", max_length=2
                    ),
                ),
                (
                    "precinct_id",
                    models.CharField(
                        db_index=True,
                        help_text="Precinct identifier (format varies by state)",
                        max_length=60,
                    ),
                ),
                (
                    "precinct_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        help_text="Precinct boundary geometry (WGS 84)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "election_year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                    ),
                ),
                (
                    "office",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("senate", "U.S. Senate"),
                            ("house", "U.S. House"),
                            ("governor", "Governor"),
                            ("state_senate", "State Senate"),
                            ("state_house", "State House"),
                            ("attorney_general", "Attorney General"),
                            ("secretary_of_state", "Secretary of State"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        help_text="Political party (DEM, REP, LIB, GRN, IND, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "candidate_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "votes",
                    models.IntegerField(
                        help_text="Vote count for this candidate/party in this precinct"
                    ),
                ),
                (
                    "total_votes",
                    models.IntegerField(
                        blank=True,
                        help_text="Total votes cast in this precinct for this office",
                        null=True,
                    ),
                ),
                (
                    "vote_share",
                    models.FloatField(
                        blank=True,
                        help_text="Fraction of total votes (0.0–1.0)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="rdh", help_text="Provenance tag", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Precinct Election Result",
                "verbose_name_plural": "Precinct Election Results",
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_special",
                    models.BooleanField(
                        default=False, help_text="True for special elections"
                    ),
                ),
                (
                    "cause_of_special",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("death", "Death"),
                            ("resignation", "Resignation"),
                            ("expulsion", "Expulsion"),
                            ("recall", "Recall"),
                            ("vacancy", "Vacancy"),
                        ],
                        default="",
                        help_text="Reason for special election (blank for regular)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Race",
                "verbose_name_plural": "Races",
            },
        ),
        migrations.CreateModel(
            name="RaceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FILING_OPEN", "Filing Period Opens"),
                            ("FILING_CLOSE", "Filing Period Closes"),
                            ("PRIMARY", "Primary Election"),
                            ("PRIMARY_RUNOFF", "Primary Runoff"),
                            ("GENERAL", "General Election"),
                            ("GENERAL_RUNOFF", "General Runoff"),
                            ("RECOUNT", "Recount"),
                            ("CERTIFICATION", "Result Certification"),
                            ("INAUGURATION", "Inauguration / Swearing In"),
                            ("COURT_RULING", "Court Ruling"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField(help_text="Date of this race event")),
                (
                    "event_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Precise start time (e.g. polls open)",
                        null=True,
                    ),
                ),
                (
                    "event_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Precise end time (e.g. polls close)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Race Event",
                "verbose_name_plural": "Race Events",
                "ordering": ["event_date"],
            },
        ),
        migrations.CreateModel(
            name="RedistrictingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_fips",
                    models.CharField(
                        db_index=True, help_text="2-digit state FIPS code", max_length=2
                    ),
                ),
                (
                    "chamber",
                    models.CharField(
                        choices=[
                            ("congress", "U.S. Congress"),
                            ("state_senate", "State Senate"),
                            ("state_house", "State House"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "cycle_year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Redistricting cycle year (2010, 2020, 2030)",
                        validators=[
                            django.core.validators.MinValueValidator(1960),
                            django.core.validators.MaxValueValidator(2040),
                        ],
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        help_text="Plan identifier or title", max_length=255
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("enacted", "Enacted"),
                            ("proposed", "Proposed"),
                            ("alternative", "Alternative"),
                            ("court_ordered", "Court-Ordered"),
                            ("commission", "Commission"),
                        ],
                        default="enacted",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("rdh", "Redistricting Data Hub"),
                            ("census", "U.S. Census Bureau"),
                            ("court", "Court"),
                            ("legislature", "Legislature"),
                            ("commission", "Commission"),
                        ],
                        default="rdh",
                        help_text="Where this plan data came from",
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, default="", help_text="URL to the original dataset"
                    ),
                ),
                (
                    "num_districts",
                    models.PositiveSmallIntegerField(
                        help_text="Total number of districts in this plan"
                    ),
                ),
                (
                    "enacted_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the plan was enacted (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        default="rdh",
                        help_text="Provenance tag for SourceAwareModel pattern",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Redistricting Plan",
                "verbose_name_plural": "Redistricting Plans",
            },
        ),
        migrations.CreateModel(
            name="ReturnSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="When this snapshot was captured"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ap", "Associated Press"),
                            ("state_sos", "Secretary of State"),
                            ("county", "County Clerk / Board of Elections"),
                            ("manual", "Manual Entry"),
                        ],
                        help_text="Source of this result data",
                        max_length=20,
                    ),
                ),
                (
                    "precincts_reporting",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("total_precincts", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pct_reporting",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of precincts reporting",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "total_ballots_counted",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("ballots_outstanding", models.BigIntegerField(blank=True, null=True)),
                (
                    "results",
                    models.JSONField(
                        default=dict,
                        help_text="Candidate results: {candidate_id: {votes, pct, party}}",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this is the certified final result",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Return Snapshot",
                "verbose_name_plural": "Return Snapshots",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office",
                    models.CharField(
                        choices=[
                            ("PRESIDENT", "President"),
                            ("US_SENATE", "U.S. Senate"),
                            ("US_HOUSE", "U.S. House"),
                            ("GOVERNOR", "Governor"),
                            ("STATE_SENATE", "State Senate"),
                            ("STATE_HOUSE", "State House"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "district_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="District number/label (e.g. '12' for CA-12, '' for at-large/statewide)",
                        max_length=20,
                    ),
                ),
                (
                    "senate_class",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Class I"), (2, "Class II"), (3, "Class III")],
                        help_text="Senate class (1, 2, or 3) — only for US_SENATE",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this seat currently exists (districts can be eliminated)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Seat",
                "verbose_name_plural": "Seats",
            },
        ),
        migrations.CreateModel(
            name="SpatioTemporalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stable identifier for this feature (unique per vintage_year)",
                        max_length=60,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of this feature", max_length=255
                    ),
                ),
                (
                    "vintage_year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="Edition year of the source dataset",
                        validators=[
                            django.core.validators.MinValueValidator(1790),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Date this feature became effective (NULL = always valid)",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this feature ceased to be effective (NULL = still valid)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provenance of this feature (e.g. TIGER/Line, GADM, OSM)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        blank=True,
                        help_text="Event geometry — polygon for affected area, point for location",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("event_start", models.DateTimeField(help_text="When the event began")),
                (
                    "event_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the event ended (NULL = ongoing or instantaneous)",
                        null=True,
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("NATURAL_DISASTER", "Natural Disaster"),
                            ("COURT_RULING", "Court Ruling"),
                            ("REDISTRICTING", "Redistricting Event"),
                            ("LEGISLATION", "Legislation"),
                            ("EXECUTIVE_ORDER", "Executive Order"),
                            ("PROTEST", "Protest / Civil Action"),
                            ("INFRASTRUCTURE", "Infrastructure Event"),
                            ("PUBLIC_HEALTH", "Public Health Event"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spatio-Temporal Event",
                "verbose_name_plural": "Spatio-Temporal Events",
            },
        ),
        migrations.CreateModel(
            name="StateElectionCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of state primary election",
                        null=True,
                    ),
                ),
                (
                    "primary_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("semi_closed", "Semi-Closed"),
                            ("semi_open", "Semi-Open"),
                            ("top_two", "Top-Two"),
                            ("top_four", "Top-Four / Ranked Choice"),
                            ("blanket", "Blanket"),
                        ],
                        default="",
                        help_text="Primary election type",
                        max_length=20,
                    ),
                ),
                (
                    "primary_runoff_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of primary runoff (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "general_date",
                    models.DateField(
                        blank=True, help_text="Date of general election", null=True
                    ),
                ),
                (
                    "general_runoff_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of general election runoff (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateField(
                        blank=True, help_text="Voter registration deadline", null=True
                    ),
                ),
                ("early_voting_start", models.DateField(blank=True, null=True)),
                ("early_voting_end", models.DateField(blank=True, null=True)),
                (
                    "mail_ballot_request_deadline",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "mail_ballot_return_deadline",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "certification_deadline",
                    models.DateField(
                        blank=True,
                        help_text="State deadline to certify results",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "State Election Calendar",
                "verbose_name_plural": "State Election Calendars",
            },
        ),
        migrations.RenameIndex(
            model_name="isochroneresult",
            new_name="siege_geo_i_travel__b1f548_idx",
            old_name="siege_geo_iso_travel_profile_idx",
        ),
        migrations.RenameIndex(
            model_name="isochroneresult",
            new_name="siege_geo_i_provide_e81b7b_idx",
            old_name="siege_geo_iso_provider_idx",
        ),
        migrations.RenameIndex(
            model_name="isochroneresult",
            new_name="siege_geo_i_compute_8ac53b_idx",
            old_name="siege_geo_iso_computed_idx",
        ),
        migrations.AddIndex(
            model_name="congressionalterm",
            index=models.Index(
                fields=["election_year"], name="siege_geo_c_electio_4d77a1_idx"
            ),
        ),
        migrations.AddField(
            model_name="districtdemographics",
            name="district",
            field=models.ForeignKey(
                help_text="Parent plan district",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demographics",
                to="siege_geo.plandistrict",
            ),
        ),
        migrations.AddField(
            model_name="plandistrictassignment",
            name="boundary_content_type",
            field=models.ForeignKey(
                help_text="Content type of the boundary model",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="precinctelectionresult",
            name="state",
            field=models.ForeignKey(
                help_text="Parent state",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="precinct_election_results",
                to="siege_geo.state",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="congressional_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="races",
                to="siege_geo.congressionalterm",
            ),
        ),
        migrations.AddField(
            model_name="raceevent",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="siege_geo.race",
            ),
        ),
        migrations.AddField(
            model_name="redistrictingplan",
            name="state",
            field=models.ForeignKey(
                help_text="Parent state",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redistricting_plans",
                to="siege_geo.state",
            ),
        ),
        migrations.AddField(
            model_name="precinctelectionresult",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to redistricting plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="precinct_results",
                to="siege_geo.redistrictingplan",
            ),
        ),
        migrations.AddField(
            model_name="plandistrictassignment",
            name="plan",
            field=models.ForeignKey(
                help_text="Parent redistricting plan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="district_assignments",
                to="siege_geo.redistrictingplan",
            ),
        ),
        migrations.AddField(
            model_name="plandistrict",
            name="plan",
            field=models.ForeignKey(
                help_text="Parent redistricting plan",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="siege_geo.redistrictingplan",
            ),
        ),
        migrations.AddField(
            model_name="returnsnapshot",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_snapshots",
                to="siege_geo.race",
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="State (NULL for PRESIDENT)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="siege_geo.state",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="races",
                to="siege_geo.seat",
            ),
        ),
        migrations.AddField(
            model_name="plandistrictassignment",
            name="seat",
            field=models.ForeignKey(
                help_text="The political seat assigned to this boundary",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="district_assignments",
                to="siege_geo.seat",
            ),
        ),
        migrations.AddField(
            model_name="spatiotemporalevent",
            name="affected_boundaries",
            field=models.ManyToManyField(
                blank=True,
                help_text="Boundaries affected by this event",
                related_name="affecting_events",
                to="siege_geo.state",
            ),
        ),
        migrations.AddField(
            model_name="raceevent",
            name="external_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to a real-world event that triggered this",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="race_events",
                to="siege_geo.spatiotemporalevent",
            ),
        ),
        migrations.AddField(
            model_name="stateelectioncalendar",
            name="congressional_term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="election_calendars",
                to="siege_geo.congressionalterm",
            ),
        ),
        migrations.AddField(
            model_name="stateelectioncalendar",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="election_calendars",
                to="siege_geo.state",
            ),
        ),
        migrations.AddIndex(
            model_name="districtdemographics",
            index=models.Index(
                fields=["district", "dataset"], name="siege_geo_d_distric_413520_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="districtdemographics",
            index=models.Index(
                fields=["year", "dataset"], name="siege_geo_d_year_92a491_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="districtdemographics",
            unique_together={("district", "dataset", "year")},
        ),
        migrations.AddIndex(
            model_name="redistrictingplan",
            index=models.Index(
                fields=["state_fips", "chamber"], name="siege_geo_r_state_f_2cd692_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="redistrictingplan",
            index=models.Index(
                fields=["cycle_year", "plan_type"],
                name="siege_geo_r_cycle_y_be1e6c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="redistrictingplan",
            unique_together={("state_fips", "chamber", "cycle_year", "plan_name")},
        ),
        migrations.AddIndex(
            model_name="precinctelectionresult",
            index=models.Index(
                fields=["state_fips", "election_year"],
                name="siege_geo_p_state_f_ae32b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="precinctelectionresult",
            index=models.Index(
                fields=["precinct_id", "election_year"],
                name="siege_geo_p_precinc_379c56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="precinctelectionresult",
            index=models.Index(
                fields=["office", "party"], name="siege_geo_p_office_6a39ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precinctelectionresult",
            index=models.Index(
                fields=["election_year"], name="siege_geo_p_electio_2447c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plandistrict",
            index=models.Index(
                fields=["plan", "district_number"],
                name="siege_geo_p_plan_id_052db0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plandistrict",
            index=models.Index(
                fields=["state_fips", "vintage_year"],
                name="siege_geo_p_state_f_c0b8b8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plandistrict",
            unique_together={("plan", "district_number")},
        ),
        migrations.AddIndex(
            model_name="returnsnapshot",
            index=models.Index(
                fields=["race", "timestamp"], name="siege_geo_r_race_id_ed6e38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnsnapshot",
            index=models.Index(
                fields=["race", "is_final"], name="siege_geo_r_race_id_c47847_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["office", "state"], name="siege_geo_s_office_6c67c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(fields=["office"], name="siege_geo_s_office_3e4698_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="seat",
            unique_together={("office", "state", "district_label")},
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["seat", "congressional_term"],
                name="siege_geo_r_seat_id_7a271a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["congressional_term"], name="siege_geo_r_congres_e67ac0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="race",
            index=models.Index(
                fields=["is_special"], name="siege_geo_r_is_spec_bc35d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plandistrictassignment",
            index=models.Index(
                fields=["plan", "seat"], name="siege_geo_p_plan_id_3db50e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="plandistrictassignment",
            index=models.Index(
                fields=["boundary_content_type", "boundary_object_id"],
                name="siege_geo_p_boundar_b29dcb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plandistrictassignment",
            unique_together={("plan", "seat")},
        ),
        migrations.AddIndex(
            model_name="spatiotemporalevent",
            index=models.Index(
                fields=["event_category"], name="siege_geo_s_event_c_271f4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spatiotemporalevent",
            index=models.Index(
                fields=["event_start"], name="siege_geo_s_event_s_eee58e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raceevent",
            index=models.Index(
                fields=["race", "event_type"], name="siege_geo_r_race_id_cbfb07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raceevent",
            index=models.Index(
                fields=["event_date"], name="siege_geo_r_event_d_8ef65f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stateelectioncalendar",
            index=models.Index(
                fields=["state", "congressional_term"],
                name="siege_geo_s_state_i_ea8be8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stateelectioncalendar",
            unique_together={("state", "congressional_term")},
        ),
    ]
