# Generated by Django 6.1 on 2026-08-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siege_geo", "0011_vtd_geoid_11_digits"),
    ]

    operations = [
        migrations.CreateModel(
            name="BargainingUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_description", models.TextField(blank=True, default="")),
                (
                    "naics_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="NAICS industry code",
                        max_length=10,
                    ),
                ),
                (
                    "soc_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of SOC occupation codes",
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bargaining Unit",
                "verbose_name_plural": "Bargaining Units",
            },
        ),
        migrations.CreateModel(
            name="ElectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tally_date", models.DateField(blank=True, db_index=True, null=True)),
                ("eligible_voters", models.PositiveIntegerField(blank=True, null=True)),
                ("votes_for", models.PositiveIntegerField(blank=True, null=True)),
                ("votes_against", models.PositiveIntegerField(blank=True, null=True)),
                ("void_ballots", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "union_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("source", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Election Result",
                "verbose_name_plural": "Election Results",
            },
        ),
        migrations.CreateModel(
            name="NLRBCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        db_index=True,
                        help_text="NLRB case number (e.g. '05-RC-123456')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        db_index=True,
                        help_text="Case type code (R, RC, CA, CB, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "case_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Employer or party name",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_index=True, default="Unknown", max_length=50
                    ),
                ),
                ("date_filed", models.DateField(blank=True, db_index=True, null=True)),
                ("date_closed", models.DateField(blank=True, null=True)),
                (
                    "region_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Region number extracted from case number",
                        null=True,
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=2
                    ),
                ),
                (
                    "union_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("unit_description", models.TextField(blank=True, default="")),
                (
                    "naics_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=10
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Data source: 'datagov', 'labordata', 'nxgen'",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "NLRB Case",
                "verbose_name_plural": "NLRB Cases",
            },
        ),
        migrations.CreateModel(
            name="ULPCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allegation", models.TextField(blank=True, default="")),
                (
                    "charging_party",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "charged_party",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "section_of_act",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="NLRA section cited (e.g. '8(a)(1)')",
                        max_length=50,
                    ),
                ),
                ("date_filed", models.DateField(blank=True, db_index=True, null=True)),
                ("source", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "ULP Charge",
                "verbose_name_plural": "ULP Charges",
            },
        ),
        migrations.RemoveIndex(
            model_name="otherspecialdistrict",
            name="siege_geo_otherspe_vy_idx",
        ),
        migrations.AlterField(
            model_name="cemeterydistrict",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="cemeterydistrict",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="countysubdivision",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="countysubdivision",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="fireprotectiondistrict",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="fireprotectiondistrict",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="hospitaldistrict",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="hospitaldistrict",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="librarydistrict",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="librarydistrict",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="mosquitoabatementdistrict",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="mosquitoabatementdistrict",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="otherspecialdistrict",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="otherspecialdistrict",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="puma",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="puma",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="redistrictingplan",
            name="enacted_date",
            field=models.DateField(
                blank=True,
                help_text="Date the plan was enacted by legislature/commission/court",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tribalarea",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="tribalarea",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="watersupplydistrict",
            name="funcstat",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Functional status code from TIGER/Line",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="watersupplydistrict",
            name="state_fips",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2-digit state FIPS code",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="otherspecialdistrict",
            index=models.Index(
                fields=["state_fips", "function_code", "vintage_year"],
                name="siege_geo_o_state_f_80aa2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="redistrictingplan",
            index=models.Index(
                fields=["state_fips", "chamber", "effective_from"],
                name="siege_geo_r_state_f_2f052d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="redistrictingplan",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="siege_geo_r_effecti_ad3f82_idx",
            ),
        ),
        migrations.AddField(
            model_name="nlrbcase",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="siege_geo.nlrbregion",
            ),
        ),
        migrations.AddField(
            model_name="electionresult",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="election_results",
                to="siege_geo.nlrbcase",
            ),
        ),
        migrations.AddField(
            model_name="bargainingunit",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bargaining_units",
                to="siege_geo.nlrbcase",
            ),
        ),
        migrations.AddField(
            model_name="ulpcharge",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ulp_charges",
                to="siege_geo.nlrbcase",
            ),
        ),
        migrations.AddIndex(
            model_name="nlrbcase",
            index=models.Index(
                fields=["case_type", "status"], name="siege_geo_n_case_ty_853640_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nlrbcase",
            index=models.Index(
                fields=["date_filed"], name="siege_geo_n_date_fi_bede91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nlrbcase",
            index=models.Index(fields=["state"], name="siege_geo_n_state_4a81fe_idx"),
        ),
        migrations.AddIndex(
            model_name="electionresult",
            index=models.Index(
                fields=["tally_date"], name="siege_geo_e_tally_d_e4fa4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bargainingunit",
            index=models.Index(
                fields=["naics_code"], name="siege_geo_b_naics_c_c57f28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ulpcharge",
            index=models.Index(
                fields=["date_filed"], name="siege_geo_u_date_fi_061d46_idx"
            ),
        ),
    ]
